# Nombre de la aplicación
spring.application.name=QAPI_FacturacionMasiva

## Puerto del servidor
server.port=8080

aws.sqs.fifo.queue.url=https://sqs.us-east-1.amazonaws.com/225711149285/uca-test-factmasiva-sqs.fifo

secret.jwt=6kz5I;[sChJz2r^zEtw*m^`"0%Nq<hN]

## spring.security.user.name=admin
## spring.security.user.password=admin

## logging.level.org.springframework.security=DEBUG
## logging.level.org.springframework.web=DEBUG

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
