spring:
    devtools:
        restart:
            enabled: false
    datasource:
        url: jdbc:oracle:thin:@18.212.57.207:1521/UCALDTES
        username: vu_sfi
        password: LJR8eFlreCKHi3FfATsJ
    cloud:
        aws:
            endpoint: http://localhost:4566
            region:
                static: us-east-1
    # Las credenciales deben ser setteadas en la consola!

aws:
    sqs:
        fifo:
            queue:
                # url: "https://sqs.us-east-1.amazonaws.com/225711149285/uca-test-factmasiva-sqs.fifo"
                # url: "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/uca-test-factmasiva-sqs.fifo"
                name: "uca-test-factmasiva-sqs.fifo"
    s3:
        bucketname: "uca-test-facturacionmasiva-auditory"
        
springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /docs

server:
  port: 8081