services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-qapi
    ports:
      - "4566:4566"            # Puerto principal de LocalStack
      #- "4510-4559:4510-4559"  # Puertos adicionales
    environment:
      - SERVICES=sqs,dynamodb,s3
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./localstack-data:/var/lib/localstack" #vol de persistencia de data
      - "/var/run/docker.sock:/var/run/docker.sock"
    #networks:
      #- qapi-network

#networks:
  #qapi-network:
    #driver: bridge
